pipeline {
    agent any

    environment {
        ANDROID_HOME = "C:/Users/SQA/AppData/Local/Android/Sdk"
        JAVA_HOME = "C:/Program Files/Java/jdk-23"
        NVM_HOME = "C:/Users/Administrator/AppData/Roaming/nvm"
        PATH = "${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'Sonda2-Credentials', branch: 'master', url: 'https://github.com/procesoseficientes/sonda-2.git'
            }
        }

        stage('Select node version') {
            steps {
                bat 'nvm use 18'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm i'
            }
        }

        stage('Build APK') {
            steps {
                bat 'npm run build:android'
            }
        }

        stage('Archive APK') {
            steps {
                archiveArtifacts artifacts: 'app/build/outputs/apk/release/app-release.apk', allowEmptyArchive: false
            }
        }
    }
}