pipeline {
    agent any

    environment {
        ANDROID_HOME = "C:/Users/SQA/AppData/Local/Android/Sdk"
        JAVA_HOME = "C:/Program Files/Java/jdk-23"
        PATH = "${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"
        NVM_HOME = "C:/Users/SQA/AppData/Roaming/nvm" // Ruta donde se instaló nvm
        PATH = "${NVM_HOME}:${NVM_HOME}/node_modules/npm:${PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'Sonda2-Credentials', branch: 'master', url: 'https://github.com/procesoseficientes/sonda-2.git'
            }
        }

        stage('Select node version') {
            steps {
                 bat '''
                    echo %NVM_HOME%
                    nvm install 18
                    nvm use 18
                    node -v
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm i'
            }
        }

        stage('Build APK') {
            steps {
                bat 'npm run build:android'
            }
        }

        stage('Archive APK') {
            steps {
                archiveArtifacts artifacts: 'app/build/outputs/apk/release/app-release.apk', allowEmptyArchive: false
            }
        }
    }
}