pipeline {
    agent any

    environment {
        ANDROID_HOME = "C:/Users/SQA/AppData/Local/Android/Sdk" // Ruta al Android SDK
        JAVA_HOME = "C:/Program Files/Java/jdk-23"           // Ruta al JDK
        PATH = "${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/procesoseficientes/sonda-2'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh './gradlew dependencies'
            }
        }

        stage('Build APK') {
            steps {
                sh './gradlew assembleRelease'
            }
        }

        stage('Archive APK') {
            steps {
                archiveArtifacts artifacts: 'app/build/outputs/apk/release/app-release.apk', allowEmptyArchive: false
            }
        }
    }
}